__default__:
    threads: 1
    n_cpu: "-pe parallel_smp {threads}"
    mem: "-l mem_free=4G"
    export_env: "-V"
    cwd: "-cwd"
    logerror: "-e {log.error}.cluster"
    log: "-o {log.output}.cluster"
    queue: "-q normal.q"

run_GBSx_PE:
    threads: 1
    mem: "-l mem_free=16G"

bwa_index:
    threads: 1
    queue: "-q short.q"

run_atropos_PE:
    threads: 6

run_atropos_SE:
    threads: 6

run_fastqc_PE:
    threads: 2
    mem: "-l mem_free=4G"

run_fastqc_SE:
    threads: 2
    mem: "-l mem_free=4G"

run_bwa_aln_PE:
    threads: 6
    mem: "-l mem_free=4G"

run_bwa_aln_SE:
    threads: 6
    mem: "-l mem_free=4G"

bwa_samse_sort_bam:
    threads: 6
    mem: "-l mem_free=4G"

bwa_sampe_sort_bam:
    threads: 6
    mem: "-l mem_free=4G"

bwa_mem_PE_sort_bam:
    threads: 6
    mem: "-l mem_free=4G"

bwa_mem_SE_sort_bam:
    threads: 6
    mem: "-l mem_free=4G"

merge_bam_directories:
    queue: "-q short.q"

samtools_idxstats:
    threads: 4
    mem: "-l mem_free=4G"

samtools_depth:
    mem: "-l mem_free=4G"

merge_idxstats:
    mem: "-l mem_free=4G"

bam_stats_to_csv:
    mem: "-l mem_free=20G"

merge_bam_stats:
    mem: "-l mem_free=4G"

picardTools_mark_duplicates:
    mem: "-l mem_free=20G"
    queue: "-q normal.q"

gatk_HaplotypeCaller:
    threads: 4
    javaMem: "8g"
    mem: "-l mem_free=12G"
    queue: "-q long.q"

gatk_GenomicsDBImport:
    javaMem: "20g"
    mem: "-l mem_free=30G"
    queue: "-q long.q"

gatk_GenotypeGVCFs_merge:
    javaMem: "30g"
    mem: "-l mem_free=40G"
    queue: "-q long.q"

create_sequence_dict:
    javaMem: "10g"
    mem: "-l mem_free=30G"

bcftools_concat:
    threads: 10
    queue: "-q short.q"
    
vcftools_filter:
    threads: 10
    queue: "-q short.q"
    
    
    
