# Master sRNA_pipeline configuration file template
# ------------------------------------------

####################
# Input output data options
'DATA':
    'directories':
        'samples_dir': "/work/sravel/mapping/fastq/"       # samples dir
        'reference_file': "/work/sravel/mapping/ref/Mycfi2_wg_ed.fasta"       # references dir
        #'reference_file': "/work/sravel/mapping/ref/scaff-test.fasta"       # references dir
        'out_dir': "/work/sravel/mapping/pop_genome_86_samples-bwa-mem/"       # Out directory
    mitochondrial_name : "mtDNA"
##################
# Pipeline options
# boolean run Atropos if True
cleanning: False
# boolean, make SNP calling (if True) or juste mapping (if False)
SNPcalling: False
# boolean, add stats mapping report if True
build_stats: True
#avail: ["mem","sampe","samse"] please select only bwa tools for moment
mapping_tools: "mem"
##############################
# Location of various software
#
# the variable must load soft on the $PATH environement
MODULES:
    "SAMTOOLS": "module load bioinfo/samtools/1.9"         # use for filter reads and convert sam to bam
    "PYTHON3": "module load system/python/3.7.3"           # Python3 >=3.6 with require libraries
    "BWA": "module load bioinfo/bwa/0.7.15"                # for make the mapping
    "ATROPOS": "module load system/python/3.7.3"           # for call atropos
    "FASTQC": "module load bioinfo/FastQC/0.11.7"          # for controle quality
    "PICARDTOOLS": "module load bioinfo/picard-tools/2.7.0"          # for controle quality
    "GATK4": "module load bioinfo/GATK/4.1.4.0"          # for controle quality
    "BCFTOOLS": "module purge && module load bioinfo/bcftools/1.9"          # for contact vcf

############################
# Misc. options for programs
PARAMS_TOOLS:
    "ATROPOS_SE": "--minimum-length 35  -q 20  -u 8  -O 10"
    "ATROPOS_PE": "--minimum-length 35  -q 20,20  -U 8  -O 10"
    "FASTQC": ""
    "BWA_ALN": ""
    "BWA_SAMSE": ""
    "BWA_SAMPE": ""
    "BWA_MEM": ""
    "SAMTOOLS_VIEW": "-bh"
    "SAMTOOLS_SORT": ""
    "SAMTOOLS_DEPTH": ""
    "PICARDTOOLS_MARK_DUPLICATES": "CREATE_INDEX=TRUE VALIDATION_STRINGENCY=SILENT"
    "GATK_HAPLOTYPECALLER": "--emit-ref-confidence GVCF --output-mode EMIT_ALL_ACTIVE_SITES -ploidy 1"
    "GATK_GENOMICSDBIMPORT": ""
    "GATK_GENOTYPEGVCFS": "-new-qual"
